title: Will Rothpletz # your name (or website title) here
logo: "/images/59686f2e-e430-4c15-805a-ab5baf5acd19.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 
  <a href="https://www.linkedin.com/in/william-rothpletz">LinkedIn</a> 
  <br>
  <a href="/pdf/William Rothpletz Resume.pdf">Resume</a>  
  <br>
  <a href="https://github.com/WilliamRoth82/">GitHub</a>  
  <br>
  
theme: jekyll-theme-minimal
